import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import { CookiesProvider } from 'next-client-cookies/server';

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased `}>
        <CookiesProvider>
          <div className="bg-white text-[#1a1a1a] dark:bg-[#1a1a1a] dark:text-[#ededed] ">
            <div className="max-w-[85rem] mx-auto ">
              <Navbar />
              {children}
              <Toaster
                position="top-center"
                reverseOrder={false}
              />
            </div>
          </div>
        </CookiesProvider>
      </body>
    </html>
  );
}



// bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-zinc-700 via-[#1a1a1a] to-black